---
- name: "Gather the package facts"
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined

- name: "Create software directory under root homedir, if it does not exist"
  file:
    path: "/root/software/"
    state: directory

- name: "Download installer package from local repository"
  get_url:
    url: "{{ software_url }}/{{ package_name }}"
    dest: "/root/software/{{ package_name }}"
    validate_certs: no
    mode: 0777

- name: "Install Oracle Java Development Kit (JDK), if not already installed"
  package:
    name: "/root/software/{{ package_name }}"
    state: present
  #when:
  #  - "'jdk-*' not in ansible_facts.packages"